namespace SpriteKind {
    export const Helicopter = SpriteKind.create()
    export const Cloud = SpriteKind.create()
    export const LandingPad = SpriteKind.create()
    export const Tree = SpriteKind.create()
    export const Diver = SpriteKind.create()
}
sprites.onOverlap(SpriteKind.Cloud, SpriteKind.Cloud, function (sprite, otherSprite) {
    Balloon.setPosition(randint(15, 140), randint(15, 100))
})
sprites.onOverlap(SpriteKind.Helicopter, SpriteKind.LandingPad, function (sprite, otherSprite) {
    sprite.vx = 0
    sprite.vy = 0
    pause(100)
    sprite.y += -2
})
sprites.onOverlap(SpriteKind.Helicopter, SpriteKind.Tree, function (sprite, otherSprite) {
    sprite.x += -1 * sprite.vx
    sprite.y += -1 * sprite.vy
    sprite.vx = 0
    sprite.vy = 0
    otherSprite.x += -1
    pause(100)
    otherSprite.x += 1
    pause(100)
    sprite.x += 6
    copter.image.flipX()
    pause(200)
    sprite.y += -1
    pause(200)
    sprite.x += -4
    pause(200)
    sprite.y += 4
})
sprites.onOverlap(SpriteKind.Helicopter, SpriteKind.Cloud, function (sprite, otherSprite) {
    sprite.x += -1 * sprite.vx
    sprite.y += -1 * sprite.vy
    sprite.vx = 0
    sprite.vy = 0
    otherSprite.x += -1
    pause(100)
    otherSprite.x += 1
})
sprites.onOverlap(SpriteKind.Helicopter, SpriteKind.Diver, function (sprite, otherSprite) {
    otherSprite.destroy(effects.smiles, 500)
})
let Balloon: Sprite = null
let copter: Sprite = null
game.splash("Cloud Bump", "control pad flying")
scene.setBackgroundColor(9)
copter = sprites.create(img`
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ......................ffff......
    .....ffff.........fffffff.......
    .......fffffffffffff............
    ...............f................
    ...............f................
    ..............ef..eee...........
    ....f.........e..eeff11.........
    ..ffffffff....eee2f.1111........
    .....f......eee222f11111........
    .....f...eee222222f11111e.......
    .....feeee22222222ff11f2e.......
    .....ee22222222222fffff2e.......
    .....e222222222222fffff2e.......
    .....ee22222222222fffff2e.......
    ......ee222222e222222ff2e.......
    .......ee22222ee2222222ee.......
    ........eeee2eee222222ee........
    ...........fe...eeeeee..........
    ...........f........f...........
    ......f....f........f.....f.....
    ......ffffffffffffffffffff......
    ................................
    ................................
    ................................
    ................................
    ................................
    `, SpriteKind.Helicopter)
copter.setStayInScreen(true)
// Create and place "clouds"  Sprites
let cloud1 = sprites.create(img`
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . 1 1 1 1 1 8 . . . . . . 
    . . . 1 1 8 8 8 1 1 1 1 1 1 . . 
    . 8 1 1 8 8 8 8 8 8 8 8 8 1 1 . 
    . 1 8 8 8 1 8 8 8 1 1 8 8 8 1 . 
    1 1 8 8 1 1 1 1 1 8 8 8 1 1 1 . 
    1 1 8 8 8 8 8 1 1 8 1 8 1 1 . . 
    . 1 1 1 1 8 8 8 8 8 8 8 1 8 . . 
    . . . . 1 1 8 8 1 1 8 8 1 . . . 
    . . . . . . 8 8 8 1 1 1 1 . . . 
    . . . . . . 1 1 1 1 . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    `, SpriteKind.Cloud)
cloud1.x = 20
cloud1.y = 30
let cloud2 = sprites.create(img`
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . 1 1 1 1 1 8 . . . . . . 
    . . . 1 1 8 8 8 1 1 1 1 1 1 . . 
    . 8 1 1 8 8 8 8 8 8 8 8 8 1 1 . 
    . 1 8 8 8 1 8 8 8 1 1 8 8 8 1 . 
    1 1 8 8 1 1 1 1 1 8 8 8 1 1 1 . 
    1 1 8 8 8 8 8 1 1 8 1 8 1 1 . . 
    . 1 1 1 1 8 8 8 8 8 8 8 1 8 . . 
    . . . . 1 1 8 8 1 1 8 8 1 . . . 
    . . . . . . 8 8 8 1 1 1 1 . . . 
    . . . . . . 1 1 1 1 . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    `, SpriteKind.Cloud)
cloud2.x = 50
cloud2.y = 65
let cloud3 = sprites.create(img`
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . 1 1 1 1 1 8 . . . . . . 
    . . . 1 1 8 8 8 1 1 1 1 1 1 . . 
    . 8 1 1 8 8 8 8 8 8 8 8 8 1 1 . 
    . 1 8 8 8 1 8 8 8 1 1 8 8 8 1 . 
    1 1 8 8 1 1 1 1 1 8 8 8 1 1 1 . 
    1 1 8 8 8 8 8 1 1 8 1 8 1 1 . . 
    . 1 1 1 1 8 8 8 8 8 8 8 1 8 . . 
    . . . . 1 1 8 8 1 1 8 8 1 . . . 
    . . . . . . 8 8 8 1 1 1 1 . . . 
    . . . . . . 1 1 1 1 . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    `, SpriteKind.Cloud)
cloud3.x = 100
cloud3.y = 40
let landing = sprites.create(img`
    58585858585858585858585858585858
    58585858585858585858585858585858
    ...............ff...............
    ...............ff...............
    ...............ff...............
    ...............ff...............
    ...............ff...............
    ...............ff...............
    ...............ff...............
    ...............ff...............
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    `, SpriteKind.LandingPad)
landing.y = 125
let Evil_Tree = sprites.create(img`
    ................
    ................
    ...76e777777e77.
    .7777eee6766777.
    7766777e66766e77
    6667667e766777e6
    6e77667e766777e6
    6e7777eee76777e6
    6ee7e77ee76777e6
    6ee77777e7667eee
    66.ee7777e767e..
    ..66e7777ee7ee..
    ..6eee777eeee...
    .....eeeee......
    ......efe.......
    ......eee.......
    ......eee.......
    ......eeee......
    ......eeee......
    ......efe.......
    ......eeee......
    .....eeeee......
    .....eeeef......
    ....ffeeee......
    ....eeeeee......
    ....eeeeee......
    ....eeeeee......
    ....eeeeee......
    ....eeeeee......
    ....efeeeee.....
    ...eeeeeeeee....
    ...eeeeeeeee....
    ...eeeeefeee....
    ..eeeeeeeeee....
    ..eeefeeeeee....
    `, SpriteKind.Tree)
Evil_Tree.setPosition(127, 103)
Balloon = sprites.create(img`
    . . 3 3 . . . . 7 7 7 7 . . . . 
    . 3 3 3 3 . . . 7 7 7 7 . . . . 
    . 3 3 3 3 . . . 7 7 7 8 8 . . . 
    . 3 3 3 3 . 5 5 . 7 8 8 8 8 . . 
    . . 3 3 . 5 5 5 5 f 8 8 8 8 . . 
    . . f . . 5 5 5 5 f 8 8 8 8 . . 
    . . . f a 5 5 5 5 f 8 8 8 8 . . 
    . . a a a . 5 5 . f . 8 8 . . . 
    . . a a a a . f . f . f . . . . 
    . . a a a a . f . f f . . . . . 
    . . . a a f . f . f . . . . . . 
    . . . f . f f f . f . . . . . . 
    . . . . f . f f f f . . . . . . 
    . . . . . f . f f . . . . . . . 
    . . . . . . f f . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    `, SpriteKind.Cloud)
Balloon.setPosition(randint(15, 140), randint(15, 100))
let SkyDiver = sprites.create(img`
    ................
    ................
    ................
    ................
    ................
    ..222222222222..
    .22222222222222.
    2222222f22222222
    ff.....f.......f
    .f.....f.....ff.
    .f.....f....ff..
    ..f....f....f...
    ..fff..f...ff...
    ....f..f...f....
    ....ff.f..ff....
    .....f.f.ff.....
    .....fff.f......
    ......ffff......
    ......44f.......
    ...dd.44.dd.....
    ....d2222d......
    .....2222.......
    .....888........
    .....8888.......
    ...dd8..8d......
    `, SpriteKind.Diver)
SkyDiver.setPosition(randint(20, 140), 0)
SkyDiver.setVelocity(randint(-5, 5), randint(1, 20))
SkyDiver.setStayInScreen(true)
game.onUpdate(function () {
    copter.vx += controller.dx(10)
    copter.vy += controller.dy(10)
})
